/**
 * BaxterClient — low-level API client for the Bella Baxter REST API.
 * Handles authentication (API key HMAC / Bearer JWT), E2EE, and all HTTP methods.
 */

import { type RequestInformation } from '@microsoft/kiota-abstractions';
import { FetchRequestAdapter } from '@microsoft/kiota-http-fetchlibrary';
// Generated by Kiota — run apps/sdk/generate.sh if this import is missing
import { BellaClient, createBellaClient } from '@bella-baxter/kiota-client';
import { BellaAuthenticationProvider } from './auth-provider.js';
import { E2EKeyPair, isE2EPayload } from './e2ee.js';
import { hexToBytes, sha256Hex, hmacSha256Hex } from './webcrypto.js';

// ── Public API types ──────────────────────────────────────────────────────────

export interface BellaSdkOptions {
  /** Base URL of the Baxter API (e.g. https://api.bella-baxter.io) */
  baxterUrl?: string;
  /**
   * Bella Baxter API key (bax-...). Obtain via WebApp or: bella apikeys create.
   * Mutually exclusive with accessToken. Falls back to BELLA_BAXTER_API_KEY env var.
   */
  apiKey?: string;
  /**
   * JWT access token for Bearer auth (injected by `bella exec` in JWT mode).
   * Mutually exclusive with apiKey. Falls back to BELLA_BAXTER_ACCESS_TOKEN env var.
   */
  accessToken?: string;
  /** Request timeout in ms (default: 10_000) */
  timeout?: number;
  /**
   * Optional name of your application, sent as X-App-Client header for audit logging.
   * Defaults to BELLA_BAXTER_APP_CLIENT env var if set, otherwise not sent.
   * Example: "my-express-api", "github-ci-deploy"
   */
  appClient?: string;
}

export interface AllEnvironmentSecretsResponse {
  environmentSlug: string;
  environmentName: string;
  secrets: Record<string, string>;
  version: number;
  lastModified: string;
}

export interface EnvironmentSecretsVersionResponse {
  environmentSlug: string;
  version: number;
  lastModified: string;
}

export interface TotpKeyInfo {
  name: string;
  issuer?: string;
  accountName?: string;
  algorithm: string;
  digits: number;
  period: number;
}

// ── Client ────────────────────────────────────────────────────────────────────

export class BaxterClient {
  private readonly kiota: BellaClient;
  private readonly baseUrl: string;
  // Only set in API key mode (used by manual sign() for E2E init)
  private readonly keyId: string | null;
  private readonly signingSecret: Uint8Array | null;
  private readonly accessToken: string | null;
  private e2ee: E2EKeyPair | null = null;

  constructor(private readonly options: BellaSdkOptions) {
    const resolvedUrl = (options.baxterUrl ?? (typeof process !== 'undefined' ? process.env['BELLA_BAXTER_URL'] : undefined) ?? 'https://api.bella-baxter.io').replace(/\/$/, '');

    // Resolve auth: explicit options → env vars
    const resolvedApiKey = options.apiKey ?? (typeof process !== 'undefined' ? process.env['BELLA_BAXTER_API_KEY'] : undefined);
    const resolvedAccessToken = options.accessToken ?? (typeof process !== 'undefined' ? process.env['BELLA_BAXTER_ACCESS_TOKEN'] : undefined);

    const appClient = options.appClient ?? (typeof process !== 'undefined' ? process.env['BELLA_BAXTER_APP_CLIENT'] : undefined);
    const authProvider = new BellaAuthenticationProvider({
      apiKey: resolvedApiKey,
      accessToken: resolvedAccessToken,
      appClient,
    });
    const adapter = new FetchRequestAdapter(authProvider);
    adapter.baseUrl = resolvedUrl;
    this.kiota = createBellaClient(adapter);
    this.baseUrl = resolvedUrl;

    if (resolvedApiKey) {
      const parts = resolvedApiKey.split('-');
      this.keyId = parts[1];
      this.signingSecret = hexToBytes(parts[2]);
      this.accessToken = null;
    } else {
      this.keyId = null;
      this.signingSecret = null;
      this.accessToken = resolvedAccessToken ?? null;
    }
  }

  private async sign(
    method: string,
    path: string,
    bodyBytes: Uint8Array = new Uint8Array(0),
  ): Promise<Record<string, string>> {
    if (this.accessToken) {
      // Bearer token mode
      return {
        'Authorization': `Bearer ${this.accessToken}`,
        'User-Agent': 'bella-js-sdk/1.0',
        'X-Bella-Client': 'bella-js-sdk',
        ...(this.options.appClient ?? (typeof process !== 'undefined' ? process.env['BELLA_BAXTER_APP_CLIENT'] : undefined)
          ? { 'X-App-Client': (this.options.appClient ?? process.env['BELLA_BAXTER_APP_CLIENT'])! }
          : {}),
      };
    }
    // HMAC mode
    const timestamp = new Date().toISOString().replace(/\.\d{3}Z$/, 'Z');
    const bodyHash = await sha256Hex(bodyBytes);
    const stringToSign = `${method}\n${path}\n\n${timestamp}\n${bodyHash}`;
    const signature = await hmacSha256Hex(this.signingSecret!, stringToSign);
    return {
      'X-Bella-Key-Id': this.keyId!,
      'X-Bella-Timestamp': timestamp,
      'X-Bella-Signature': signature,
      'User-Agent': 'bella-js-sdk/1.0',
      'X-Bella-Client': 'bella-js-sdk',
      ...(this.options.appClient ?? (typeof process !== 'undefined' ? process.env['BELLA_BAXTER_APP_CLIENT'] : undefined)
        ? { 'X-App-Client': (this.options.appClient ?? process.env['BELLA_BAXTER_APP_CLIENT'])! }
        : {}),
    };
  }

  private async fetchJson<T>(
    path: string,
    extraHeaders?: Record<string, string>,
  ): Promise<T> {
    const url = `${this.baseUrl}${path}`;
    const sigHeaders = await this.sign('GET', path);
    let resp: Response;
    try {
      resp = await fetch(url, {
        headers: { Accept: 'application/json', ...sigHeaders, ...extraHeaders },
        signal: this.options.timeout
          ? AbortSignal.timeout(this.options.timeout)
          : undefined,
      });
    } catch (err: unknown) {
      const cause = err instanceof Error ? err : new Error(String(err));
      // undici wraps the real error in cause.cause — check full chain
      const causeMsg = [cause.message, (cause as NodeJS.ErrnoException & { cause?: Error }).cause?.message ?? ''].join(' ');
      const isNotFound = causeMsg.includes('ENOTFOUND') || causeMsg.includes('getaddrinfo');
      const isTimeout = causeMsg.includes('TimeoutError') || cause.name === 'TimeoutError';
      if (isNotFound) {
        throw new Error(
          `Cannot reach Bella Baxter API at ${this.baseUrl}.\n` +
          '  Check that BELLA_BAXTER_URL is correct and the service is running.',
        );
      }
      if (isTimeout) {
        throw new Error(
          `Bella Baxter API request timed out (${this.options.timeout}ms).\n` +
          '  Increase the timeout or check your network connectivity.',
        );
      }
      throw new Error(`Bella Baxter API request failed: ${cause.message}`);
    }
    if (!resp.ok) {
      const hints: Record<number, string> = {
        401: 'Your API key is invalid or expired. Regenerate it in the Bella Baxter WebApp under Settings → API Keys.',
        403: 'Access denied. Check that your API key has access to this project/environment.',
        404: `Resource not found: ${path}\n  Check that the project slug and environment slug are correct.`,
        429: 'Rate limit exceeded. Reduce polling frequency or contact support.',
        500: 'Bella Baxter API server error. Check the service status or try again.',
      };
      const hint = hints[resp.status];
      const msg = hint
        ? `Bella API error ${resp.status}: ${hint}`
        : `Bella API error ${resp.status}: ${path}`;
      throw new Error(msg);
    }
    return resp.json() as Promise<T>;
  }

  /**
   * Initialize the client (generates E2EE keypair).
   * Call once before use, or use {@link createBaxterClient} which calls it automatically.
   */
  async init(): Promise<this> {
    this.e2ee = await E2EKeyPair.generate();
    return this;
  }

  /**
   * GET /api/v1/projects/{projectSlug}/environments/{envSlug}/secrets
   * Fetches all secrets for the environment across all providers.
   * The response is always E2EE-decrypted transparently.
   */
  async getAllSecrets(
    projectSlug: string,
    envSlug: string,
  ): Promise<AllEnvironmentSecretsResponse> {
    const path = `/api/v1/projects/${encodeURIComponent(projectSlug)}/environments/${encodeURIComponent(envSlug)}/secrets`;
    if (!this.e2ee)
      throw new Error(
        'BaxterClient not initialized — call init() or use createBaxterClient()',
      );
    const extraHeaders: Record<string, string> = {
      'X-E2E-Public-Key': this.e2ee.publicKeyB64,
    };

    const raw = await this.fetchJson<Record<string, unknown>>(
      path,
      extraHeaders,
    );

    if (isE2EPayload(raw)) {
      const parsed = await this.e2ee.decryptRaw(raw as any) as Record<string, unknown>;

      if (
        parsed && typeof parsed === 'object' && !Array.isArray(parsed) &&
        'secrets' in parsed && typeof parsed['secrets'] === 'object'
      ) {
        return parsed as unknown as AllEnvironmentSecretsResponse;
      }

      const secrets = await this.e2ee.decrypt(raw as any);
      return {
        environmentSlug: envSlug,
        environmentName: '',
        secrets,
        version: 0,
        lastModified: new Date().toISOString(),
      };
    }

    return raw as unknown as AllEnvironmentSecretsResponse;
  }

  /**
   * GET /api/v1/projects/{projectSlug}/environments/{envSlug}/secrets/version
   * Lightweight version check — returns only version + lastModified.
   */
  async getSecretsVersion(
    projectSlug: string,
    envSlug: string,
  ): Promise<EnvironmentSecretsVersionResponse> {
    const path = `/api/v1/projects/${encodeURIComponent(projectSlug)}/environments/${encodeURIComponent(envSlug)}/secrets/version`;
    return this.fetchJson<EnvironmentSecretsVersionResponse>(path);
  }

  /**
   * GET /api/v1/projects/{projectSlug}/environments/{envSlug}/totp
   * List TOTP key metadata for an environment.
   */
  async listTotpKeys(
    projectSlug: string,
    envSlug: string,
  ): Promise<TotpKeyInfo[]> {
    const path = `/api/v1/projects/${encodeURIComponent(projectSlug)}/environments/${encodeURIComponent(envSlug)}/totp`;
    return this.fetchJson<TotpKeyInfo[]>(path);
  }

  /**
   * GET /api/v1/projects/{projectSlug}/environments/{envSlug}/totp/{name}/code
   * Get the current 6-digit TOTP code for a named key.
   */
  async getTotpCode(
    projectSlug: string,
    envSlug: string,
    keyName: string,
  ): Promise<string> {
    const path = `/api/v1/projects/${encodeURIComponent(projectSlug)}/environments/${encodeURIComponent(envSlug)}/totp/${encodeURIComponent(keyName)}/code`;
    const resp = await this.fetchJson<{ code: string }>(path);
    return resp.code;
  }

  /** The underlying Kiota client — use for full admin API access. */
  get client(): BellaClient {
    return this.kiota;
  }

  /**
   * GET /api/v1/keys/me — Discover project + environment context from the authenticated API key.
   */
  async discoverContext(): Promise<{ projectSlug: string; environmentSlug: string; role: string }> {
    const resp = await this.fetchJson<{
      keyId: string;
      role: string;
      projectSlug: string | null;
      environmentSlug: string | null;
    }>('/api/v1/keys/me');

    if (!resp.projectSlug) {
      throw new Error(
        '[Bella] GET /api/v1/keys/me returned no projectSlug.\n' +
        'This API key may not be scoped to a project. Pass projectSlug explicitly.',
      );
    }
    if (!resp.environmentSlug) {
      throw new Error(
        '[Bella] GET /api/v1/keys/me returned no environmentSlug.\n' +
        'This API key may not be scoped to an environment. Pass environmentSlug explicitly.',
      );
    }

    return {
      projectSlug: resp.projectSlug,
      environmentSlug: resp.environmentSlug,
      role: resp.role,
    };
  }
}

// ── Factory ───────────────────────────────────────────────────────────────────

/** Create and initialize a pre-configured Baxter API client. */
export async function createBaxterClient(
  options: BellaSdkOptions,
): Promise<BaxterClient> {
  return new BaxterClient(options).init();
}
