// auto-generated by: bella secrets generate typescript --declaration
// project: awesome/dev
// generated: 2026-03-13 00:21:16 UTC
// DO NOT edit manually — re-run bella secrets generate typescript --declaration to update.
// Safe to commit: contains key names only, never secret values.
//
// Import BELLA_COERCIONS and pass as `coercions` to createBellaConfig() so the
// Proxy returns number/boolean at runtime instead of raw strings.
//
// Example:
//   import { BELLA_COERCIONS } from './bella-coercions.js';
//   await initBella({ ..., coercions: BELLA_COERCIONS });

export const BELLA_COERCIONS = {
  ENABLE_FEATURES: 'boolean',
  PORT: 'number',
} as const satisfies Record<string, 'number' | 'boolean'>;
