// auto-generated by: bella secrets generate typescript --declaration
// project: awesome/dev
// generated: 2026-03-13 00:21:16 UTC
// DO NOT edit manually — re-run bella secrets generate typescript --declaration to update.
// Safe to commit: contains key names only, never secret values.
//
// TypeScript picks this up automatically via tsconfig 'include'.
// No import needed in route/controller files — types are available project-wide.
//
// ⚠️  ts-node / tsx users: add this to your entry file (e.g. main.ts / server.ts):
//   /// <reference path="./bella-secrets.d.ts" />
//   (ts-node only includes imported files; tsconfig include is ignored at runtime)
//
// Runtime coercions are in bella-coercions.ts — import that once in your framework setup.

export {}; // required: makes this a module so 'declare global' is valid

declare global {
  interface BellaSecrets {
    APP_CONFIG: string;
    APP_ID: string;
    DATABASE_URL: string;
    ENABLE_FEATURES: boolean;
    EXTERNAL_API_KEY: string;
    /** Gleap service */
    GLEAP_API_KEY: string;
    PORT: number;
  }
}
